# -*- coding: utf-8 -*-
"""Dog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12K06JAO44BmktDRtYzvapnH986VMyYBU
"""

"""
OOP
Class: a user defined "blueprint" or prototype from which objects will be created
Why?  Allows a way for you to bundle data and functionality

Rules for Classes:
1. Classes are created with the keyword class
2. Attributes are the variables that belong to class
3. Attributes are always public and can be accessed using dot (.) operator:  i.e.:  MyClass.MyAttribute
4. Attributes can be made NOT directly visible by adding a double underscore to their name.  MyClass.__HiddenAttribute
*** variable in a Class is called an attribute
*** function in a Class is called a Method

class ClassName:
  # statement 1
  # ...
  # statement n

class DrLee:
  # Class Level Variables
  # Method 1
  # Method 2
  # etc.
"""
class Dog:
  # Class Variable
  animal = 'dog'

  # Initialization method (sometimes called a Constructor)
  def __init__(self,breed):
    # Instance Variables
    self.breed = breed
  # Adds another method
  def setColor(self,color):
    self.color = color
  def getColor(self):
    return self.color